### ISSUE TITLE
categorizing questions

### ISSUE THREAD

**Issue by mahlashrifi** [mahlashrifi/CE101-C#1]
This issue is for organizing and categorizing the homework questions of the basics programming course of previous years.
First, the questions are filled in the [sheet](https://docs.google.com/spreadsheets/d/1SAPncbl116FTfDpmxd_Duw4hvQ280_bsEuRlWDDcNFU/edit?usp=sharing) and after completing each topic relevant md file  should be update . ( 4 terms is going to be check : Fall-2015 / Fall-2016 / Fall-2017/Fall-2020 )

Descriptions :
 Each checked file means that the corresponding question is entered in the sheet

## ***Fall-2015***

   - [x] **HW-3**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P5

        
   - [x] **HW-4**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
    
        
   - [x] **HW-5**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
       
   - [x] **HW-7**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P5

 

## ***Fall-2016***

   - [x] **HW-1**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
        - [x] P8

   - [x] **HW-2**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        
   - [x] **HW-3**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
    
        
   - [x] **HW-4**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
       
   - [x] **HW-5**
        - [x] P1
        - [x] P2-a
        - [x] P2-b
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
   

## ***Fall-2017***

   - [x] **HW-2**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6

   - [x] **HW-3**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5

        
   - [x] **HW-4**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
   
   
   - [x] **HW-5**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P4
        - [x]  P5
        - [x]  P6

   - [x] **HW-7**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] p6

## ***Fall-2019***

   - [x] **HW-0**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
        - [x] P8
        - [x] P9

## ***Fall-2020***

   - [x] **HW-1**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7

   - [x] **HW-2**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P5
        - [x] P6
        - [x] p7
        - [x] P8
        - [x] P9

        
   - [x] **HW-3**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P5
        - [x] P6
        - [x] p7
        - [x] P8
   
   
   - [x] **HW-4**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P5

   - [x] **HW-5**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P5

   - [x] **HW-6**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P5

**Comment by mahlashrifi** [comment]
The final editing of the sheet was done and completed ^_^ (@Pmoonesi  @mina-beiki   @Amirparsa-Sal  @FarshidNooshi  thanks 🎉✨😀)

**Comment by Amirparsa-Sal** [comment]
Its been a great pleasure to work with you guys :D (@Pmoonesi @mahlashrifi @mina-beiki @FarshidNooshi )

**Comment by Pmoonesi** [comment]
Don't be tired guys :DDD
